# Generated by Django 5.1.2 on 2024-10-24 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Financials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('variable', models.CharField(max_length=255)),
                ('value', models.FloatField()),
            ],
            options={
                'db_table': 'spx"."financials',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=255)),
                ('security', models.CharField(max_length=255)),
                ('gics_sector', models.CharField(max_length=255)),
                ('gics_sub_industry', models.CharField(max_length=255)),
                ('headquarters_location', models.CharField(max_length=255)),
                ('date_added', models.DateField()),
                ('cik', models.IntegerField()),
                ('founded', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'spx"."info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Prices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('ticker', models.CharField(max_length=255)),
                ('metric', models.CharField(max_length=255)),
                ('value', models.FloatField()),
            ],
            options={
                'db_table': 'spx"."prices',
                'managed': False,
            },
        ),
    ]
